name: construction
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  flutter_hooks: ^0.20.5
  # get_it: ^8.0.3
  gap: ^3.0.1
  go_router: ^14.8.0
  nb_utils: ^7.1.3
  intl: ^0.19.0
  flutter_form_builder: ^9.7.0
  image_picker: ^1.1.2
  
  hoagsource:
    git:
      url: 'https://github.com/quochoang228/hoagsource.git'
      ref: 'main'
  wolt_modal_sheet: ^0.11.0

  logs:
    git:
      url: https://github.com/quochoang228/logs.git
      ref: main

  auth:
    git:
      url: https://github.com/quochoang228/auth.git
      ref: main

  ds:
    git:
      url: https://github.com/quochoang228/ds.git
      ref: main

  ag:
    git:
      url: https://github.com/quochoang228/ag.git
      ref: main

  di:
    git:
      url: https://github.com/quochoang228/di.git
      ref: main

  router:
    git:
      url: https://github.com/quochoang228/router.git
      ref: main

  cdn:
    git:
      url: https://github.com/quochoang228/cdn.git
      ref: main
    
  utils:
    git:
      url: https://github.com/quochoang228/utils.git
      ref: main

  storage:
    git:
      url: https://github.com/quochoang228/storage.git
      path: storage
      ref: main

  persistent_storage:
    git:
      url: https://github.com/quochoang228/storage.git
      path: persistent_storage
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
